
import { Inter } from "next/font/google";
import "@/src/styles/global.css";
import "@/src/styles/fonts.css";
import Providers from "@/src/contexts/Providers";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  // useUserStatus();
  return (
    <html lang="en">
      <head>
        <title>LeadTym</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/onboard/smalllogo.svg" />
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </head>
      <body className={inter.className}>
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
