name: Next.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps: 
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup environment variables
      run: |
        touch .env
        echo "${{ secrets.REACTUI_SERVICE_ENV }}" > .env

    - name: Build Next.js project
      run: npm run build

    - name: Start Next.js app
      run: |
        pm2 restart Leadtym_phase3_reactui || pm2 start npm --name "Leadtym_phase3_reactui" -- run start
